### ISSUE TITLE
Cosas por hacer en MyChat

### ISSUE THREAD

**Issue by NotKirzu** [CraterMaik/myChat#1]
1. **Arreglar** el tamaño de los emojis.
    - Si el mensaje contiene un texto aparte del emoji, el emoji debe hacerse más pequeño en vez de tener el mismo tamaño.

2. **Cambiar** el formato de los emojis.
    - Si el emoji es animado, el formato debe ser GIF en vez de PNG.

**Comment by CraterMaik** [comment]
a ok

**Comment by NotKirzu** [comment]
:sucaritas:

**Comment by CraterMaik** [comment]
hecho
