### ISSUE TITLE
[Sugerencia] Historial de mensajes

### ISSUE THREAD

**Issue by Tau5** [CraterMaik/myChat#14]
Sería genial que el cliente o el servidor guardaran los mensajes entrantes, así al volver a abrir la web, podrás ver los mensajes anteriores.

Hay dos formas que veo de solucionarlo:

Desde el cliente
-----------------

Se podría guardar con las tecnologías web existentes los mensajes que entran, el problema de esto es que no se guardarían los mensajes que lleguen mientras el cliente está cerrado

Desde el servidor
-------------------

Se podrían guardar los mensajes en el servidor, de tal manera que una vez iniciada la sesión en el cliente, el cliente envíe una petición al servidor para que reciba los últimos x mensajes del canal que quiere ver.

**Comment by MARCROCK22** [comment]
<:brutal:683077106506268723>

**Comment by Santi24Yt** [comment]
> <:brutal:683077106506268723>

<:hipotenusa:769374548986036254>

**Comment by CraterMaik** [comment]
done
