### ISSUE TITLE
Añadir cooldown

### ISSUE THREAD

**Issue by ghost** [CraterMaik/myChat#7]
Basicamente el cooldown serviria para no provocar api abuse
![image](https://user-images.githubusercontent.com/66977521/103977969-28993300-5159-11eb-87a4-259680870d65.png)
[La imagen no es de mybot]
El cooldown se podria especificar en el env

**Comment by AndreMor8** [comment]
Arreglado en e19dd04abee86fa646eac52a9dd5b1c035843078

Aunque en vez de configurarse en el .env el canal lo decidirá via rateLimitPerUser
